### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [KJJones13/mod_0_skills#1]
@KJJones13 overall, nice work on this! There are a few changes I'd like for you to make before we consider you `technical ready`. I think that your class 1 and class 1 example object look great.
* [x] the numberOfChairs attribute in your class 2 is something I'd expect to live on the Table class
* [x] Your class 2, would be better suited as a Chair class. 
  * [x] Keeping in mind then that attributes and methods apply to only one instance, how would that change your attributes and methods?

**Comment by KJJones13** [comment]
Thanks for the feedback. I realize an instance of a class makes more sense as a singular object. I updated class_2 and class_2_example_object files to reflect a singular object `chair`. 

Please let me know if there are any other changes.
